/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'oklch(.98 0 0)',
        surface: 'oklch(.98 0 0)',
        'surface-bright': 'oklch(.98 0 0)',
        'surface-dim': 'oklch(.85 0 0)',
        'surface-variant': 'oklch(.88 0 0)',
        'surface-container-lowest': 'oklch(1 0 0)',
        'surface-container-low': 'oklch(.96 0 0)',
        'surface-container': 'oklch(.94 0 0)',
        'surface-container-high': 'oklch(.92 0 0)',
        'surface-container-highest': 'oklch(.88 0 0)',
        'surface-tint': 'oklch(.65 .2 280)',
        'on-surface': 'oklch(.15 0 0)',
        'on-background': 'oklch(.15 0 0)',
        'on-surface-variant': 'oklch(.45 0 0)',
        primary: 'oklch(.15 0 0)',
        'on-primary': 'oklch(.98 0 0)',
        'primary-container': 'oklch(.92 0 0)',
        'on-primary-container': 'oklch(.15 0 0)',
        'primary-fixed': 'oklch(.92 0 0)',
        'primary-fixed-dim': 'oklch(.75 0 0)',
        'on-primary-fixed': 'oklch(.15 0 0)',
        'on-primary-fixed-variant': 'oklch(.45 0 0)',
        'inverse-primary': 'oklch(.75 0 0)',
        secondary: 'oklch(.45 0 0)',
        'on-secondary': 'oklch(.98 0 0)',
        'secondary-container': 'oklch(.92 0 0)',
        'on-secondary-container': 'oklch(.45 0 0)',
        'secondary-fixed': 'oklch(.92 0 0)',
        'secondary-fixed-dim': 'oklch(.75 0 0)',
        'on-secondary-fixed': 'oklch(.15 0 0)',
        'on-secondary-fixed-variant': 'oklch(.45 0 0)',
        tertiary: 'oklch(.45 0 0)',
        'on-tertiary': 'oklch(.98 0 0)',
        'tertiary-container': 'oklch(.75 0 0)',
        'on-tertiary-container': 'oklch(.15 0 0)',
        'tertiary-fixed': 'oklch(.92 0 0)',
        'tertiary-fixed-dim': 'oklch(.75 0 0)',
        'on-tertiary-fixed': 'oklch(.15 0 0)',
        'on-tertiary-fixed-variant': 'oklch(.45 0 0)',
        outline: 'oklch(.55 0 0)',
        'outline-variant': 'oklch(.88 0 0)',
        'inverse-surface': 'oklch(.2 0 0)',
        'inverse-on-surface': 'oklch(.96 0 0)',
        error: '#ba1a1a',
        'on-error': 'oklch(1 0 0)',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        accent: 'oklch(.65 .2 280)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        md: '2rem',
        'container-max': '1440px',
        unit: '4px',
        gutter: '24px',
        lg: '4rem',
        xs: '0.5rem',
        sm: '1rem',
        xl: '8rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'heading-lg': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'heading-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-2xl': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-xl': ['60px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
