/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#22005d',
        'surface-container': '#f2ecf4',
        'inverse-on-surface': '#f5eff7',
        'on-tertiary-container': '#503d00',
        'surface-container-high': '#ece6ee',
        'on-secondary-container': '#645a7d',
        'on-primary-fixed-variant': '#4f378a',
        'tertiary-container': '#c9a74d',
        'on-primary-container': '#e0d2ff',
        tertiary: '#765b00',
        'secondary-fixed-dim': '#cdc0e9',
        'surface-dim': '#ded8e0',
        'on-tertiary-fixed': '#241a00',
        'on-error-container': '#93000a',
        'primary-container': '#6750a4',
        'primary-fixed-dim': '#cfbcff',
        outline: '#7a7582',
        'on-surface': '#1d1b20',
        'surface-container-low': '#f8f2fa',
        'surface-container-highest': '#e6e0e9',
        secondary: '#63597c',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'on-secondary-fixed': '#1f1635',
        background: '#fdf7ff',
        'surface-tint': '#6750a4',
        'surface-variant': '#e6e0e9',
        'on-background': '#1d1b20',
        'primary-fixed': '#e9ddff',
        'on-error': '#ffffff',
        'on-surface-variant': '#494551',
        'tertiary-fixed': '#ffdf93',
        'surface-bright': '#fdf7ff',
        'on-secondary-fixed-variant': '#4b4263',
        'inverse-primary': '#cfbcff',
        'on-primary': '#ffffff',
        'inverse-surface': '#322f35',
        'tertiary-fixed-dim': '#e7c365',
        'secondary-fixed': '#e9ddff',
        'on-tertiary-fixed-variant': '#594400',
        'secondary-container': '#e1d4fd',
        surface: '#fdf7ff',
        'on-tertiary': '#ffffff',
        primary: '#4f378a',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#cbc4d2',
        'on-secondary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        md: '2rem',
        'container-max': '1440px',
        unit: '4px',
        gutter: '24px',
        lg: '4rem',
        xs: '0.5rem',
        sm: '1rem',
        xl: '8rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'heading-lg': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'heading-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-2xl': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-xl': ['60px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
