/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#faf8ff',
        surface: '#faf8ff',
        'surface-bright': '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-variant': '#dae2fd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-tint': '#494bd6',
        'on-surface': '#131b2e',
        'on-background': '#131b2e',
        'on-surface-variant': '#464554',
        primary: '#4648d4',
        'on-primary': '#ffffff',
        'primary-container': '#6063ee',
        'on-primary-container': '#fffbff',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'inverse-primary': '#c0c1ff',
        secondary: '#006591',
        'on-secondary': '#ffffff',
        'secondary-container': '#c9e6ff',
        'on-secondary-container': '#004666',
        'secondary-fixed': '#c9e6ff',
        'secondary-fixed-dim': '#89ceff',
        'on-secondary-fixed': '#001e2f',
        'on-secondary-fixed-variant': '#004c6e',
        tertiary: '#904900',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b55d00',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#ffb783',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#703700',
        outline: '#767586',
        'outline-variant': '#c7c4d7',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        accent: '#4648d4',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        md: '2rem',
        'container-max': '1440px',
        unit: '4px',
        gutter: '24px',
        lg: '4rem',
        xs: '0.5rem',
        sm: '1rem',
        xl: '8rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'heading-lg': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'heading-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-2xl': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-xl': ['60px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
